
peridotite:
	bash run_project.bash peridotite_hp02 peridotite_hp02   solution_model.dat
	bash run_project.bash peridotite_hpha02 peridotite_hpha02   solution_model.dat
	bash run_project.bash peridotite_stx11 peridotite_stx11 stx11_solution_model.dat

dunite:
	bash run_project.bash dunite_hp02 dunite_hp02  solution_model.dat
	bash run_project.bash dunite_hpha02 dunite_hpha02  solution_model.dat
	bash run_project.bash dunite_stx11 dunite_stx11 stx11_solution_model.dat


	